### ISSUE TITLE
emphasize that PAC is not inflexible earlier

### ISSUE THREAD

**Issue by aaronpeikert** [aaronpeikert/repro-tutorial#237]

**Comment by cjvanlissa** [comment]
Yes; in fact, I think that we should emphasize that commits with necessary changes are expected, and should be accompanied by a changelog (consider suggesting a separate file with running changelog)

**Comment by brandmaier** [comment]
Yes. You put that point very well in your talk, @aaronpeikert. Everyone will likely change their PAC in a few places. The multicollinearity issue is a good one that we could state as an example in the text. In that case, it is OK to deviate from the exact plan and remove a variable from the analysis. But document it well. Not sure whether a changelog is a good idea because then we have two places (the VCS and the changelog) that may be inconsistent. But one could aim for a human-readable summary (which does not claim to be complete).
